#!/bin/sh

case $USER in
	root) USER=postgres ;;
esac

pg_buildext \
	-o 'shared_preload_libraries=pg_squeeze' \
	-o 'wal_level=logical' \
	virtualenv << EOF
		set -eux
		psql -c 'create extension pg_squeeze'
		test/concurrency --user $USER
EOF
